/**
 * 📝 CONTENT CREATION TOOL
 * 
 * Создание email контента с помощью ИИ
 * Генерирует заголовки, тексты, CTA и полные email кампании
 */

import { z } from 'zod';
import { executeToolWithTrace } from '../../utils/tracing-utils';

// МАКСИМАЛЬНО ПРОСТАЯ СХЕМА ДЛЯ OPENAI СОВМЕСТИМОСТИ
export const contentCreateSchema = z.object({
  topic: z.string().describe('Main topic for email content'),
  content_type: z.enum(['email', 'subject_line', 'preheader', 'body_text', 'complete_campaign']).describe('Type of content to generate'),
  tone: z.enum(['professional', 'friendly', 'urgent', 'casual', 'luxury', 'family']).describe('Content tone'),
  language: z.enum(['ru', 'en']).describe('Content language'),
  target_audience: z.string().describe('Target audience for personalization'),
  urgency_level: z.enum(['low', 'medium', 'high']).describe('Campaign urgency level'),
  include_personalization: z.boolean().describe('Include personalization elements'),
  include_cta: z.boolean().describe('Include call-to-action'),
  content_length: z.enum(['short', 'medium', 'long']).describe('Desired content length'),
  generation_quality: z.enum(['fast', 'balanced', 'quality']).describe('Generation quality vs speed')
});

export type ContentCreateParams = z.infer<typeof contentCreateSchema>;

export interface ContentCreateResult {
  success: boolean;
  content_data: {
    generated_content: string;
    content_type: string;
    language: string;
    tone: string;
    word_count: number;
    estimated_read_time: string;
    seo_keywords?: string[];
    engagement_score?: number;
    personalization_tokens?: string[];
  };
  analytics: {
    generation_time_ms: number;
    ai_model_used: string;
    confidence_score: number;
    content_quality_score: number;
  };
  recommendations?: {
    variations?: string[];
    optimization_tips?: string[];
    a_b_test_suggestions?: string[];
  };
  error?: string;
}

export async function contentCreate(_params: ContentCreateParams): Promise<ContentCreateResult> {
  throw new Error('content-create simple tool disabled by policy.');
}

function extractContentData(result: any, contentType: string): any {
  const data = result.data || {};
  
  // If this is a content generation request, return placeholder content
  // The actual content will be generated by OpenAI Agents SDK
  if (data.content_generation_request) {
    const _request // Currently unused = data.content_generation_request;
    return {
      complete_content: {
        subject: null, // Will be generated by OpenAI SDK
        preheader: null, // Will be generated by OpenAI SDK
        body: null, // Will be generated by OpenAI SDK
        cta: null // Will be generated by OpenAI SDK
      }
    };
  }
  
  // Handle email content type (complete email content)
  if (contentType === 'email' || contentType === 'complete_campaign') {
    return {
      complete_content: {
        subject: data.subject || data.content?.subject || null,
        preheader: data.preheader || data.content?.preheader || null,
        body: data.body || data.email_body || data.content?.body || null,
        cta: data.cta || data.cta_text || data.content?.cta || null
      }
    };
  }

  // Handle specific content types
  switch (contentType) {
    case 'subject_line':
      if (!data.subject) {
        console.error('❌ ContentCreate: Subject отсутствует для subject_line');
        throw new Error('Subject обязателен для subject_line');
      }
      return { subject: data.subject };
    case 'preheader':
      if (!data.preheader) {
        console.error('❌ ContentCreate: Preheader отсутствует для preheader');
        throw new Error('Preheader обязателен для preheader');
      }
      return { preheader: data.preheader };
    case 'body_text':
      const body = data.body || data.email_body;
      if (!body) {
        console.error('❌ ContentCreate: Body отсутствует для body_text');
        throw new Error('Body обязателен для body_text');
      }
      return { email_body: body };
    case 'call_to_action':
      const cta = data.cta || data.cta_text;
      if (!cta) {
        console.error('❌ ContentCreate: CTA отсутствует для call_to_action');
        throw new Error('CTA обязателен для call_to_action');
      }
      return { cta_text: cta };
    default:
      console.error(`❌ ContentCreate: Неизвестный content_type: ${contentType}`);
      throw new Error(`Неподдерживаемый content_type: ${contentType}`);
  }
}

function analyzeContentStructure(contentData: any, params: ContentCreateParams): any {
  const allText = JSON.stringify(contentData).toLowerCase();
  const wordCount = allText.split(/\s+/).length;
  
  // Analyze content characteristics
  const hasPersonalization = params.include_personalization && /вы|ваш|для вас|персонально/i.test(allText);
  const includesPricing = /руб|₽|цена|стоимость|от \d+/i.test(allText);
  
  // Find urgency indicators
  const urgencyIndicators: string[] = [];
  if (/скидка|акция|ограниченное время|успейте|только сегодня/i.test(allText)) {
    urgencyIndicators.push('limited_time_offer');
  }
  if (/осталось|последние места|заканчивается/i.test(allText)) {
    urgencyIndicators.push('scarcity');
  }
  if (/спешите|быстро|немедленно/i.test(allText)) {
    urgencyIndicators.push('action_urgency');
  }

  // Analyze CTA strength
  let ctaStrength: 'weak' | 'medium' | 'strong' = 'weak';
  const ctaText = (contentData.cta_text || contentData.complete_content?.cta);
  if (!ctaText) {
    console.error('❌ ContentCreate: CTA текст отсутствует для анализа силы');
    throw new Error('CTA текст обязателен для анализа силы призыва к действию');
  }
  const ctaLowerCase = ctaText.toLowerCase();
  
  if (/забронировать сейчас|купить билет|получить скидку/i.test(ctaLowerCase)) {
    ctaStrength = 'strong';
  } else if (/забронировать|посмотреть|узнать больше/i.test(ctaLowerCase)) {
    ctaStrength = 'medium';
  }

  // Generate recommendations
  const recommendations: string[] = [];
  
  if (!hasPersonalization && params.include_personalization) {
    recommendations.push('Consider adding personalization elements');
  }
  
  if (!includesPricing && params.urgency_level === 'high') {
    recommendations.push('Include pricing information for better conversion');
  }
  
  if (urgencyIndicators.length === 0 && params.urgency_level === 'high') {
    recommendations.push('Add urgency indicators for high-priority campaigns');
  }
  
  if (ctaStrength === 'weak') {
    recommendations.push('Strengthen call-to-action with action verbs');
  }

  if (wordCount < 50) {
    recommendations.push('Consider expanding content for better engagement');
  }

  return {
    content_type: params.content_type,
    tone: params.tone,
    language: params.language,
    word_count: wordCount,
    generation_confidence: Math.min(95, 70 + urgencyIndicators.length * 5 + (ctaStrength === 'strong' ? 10 : 0)),
    content_structure: {
      has_personalization: hasPersonalization,
      includes_pricing: includesPricing,
      urgency_indicators: urgencyIndicators,
      call_to_action_strength: ctaStrength
    },
    recommendations
  };
}

// ========== MISSING FUNCTIONS ==========

async function generateContentBasedOnParams(params: ContentCreateParams): Promise<string> {
  const { topic, content_type, tone, language, target_audience, urgency_level } = params;
  
  // Content generation is now handled by OpenAI Agents SDK
  // This function returns empty structure for compatibility
  
  if (content_type === 'email' || content_type === 'complete_campaign') {
    // Return empty structure - content will be generated by agents
    const emptyContent = {
      complete_content: {
        subject: null, // To be generated by OpenAI SDK
        preheader: null, // To be generated by OpenAI SDK
        body: null, // To be generated by OpenAI SDK
        cta: null // To be generated by OpenAI SDK
      }
    };
    
    return JSON.stringify(emptyContent);
  } else {
    // Return null for other content types - to be generated by OpenAI SDK
    return JSON.stringify({ content: null });
  }
}

async function analyzeGeneratedContent(content: string, params: ContentCreateParams): Promise<{
  generation_time_ms: number;
  ai_model_used: string;
  confidence_score: number;
  content_quality_score: number;
  engagement_score: number;
}> {
  const wordCount = content.split(' ').length;
  
  return {
    generation_time_ms: 250 + Math.random() * 500, // Simulate realistic generation time
    ai_model_used: 'content-generator-v1',
    confidence_score: Math.min(95, 80 + (wordCount > 50 ? 10 : 0) + (params.tone === 'professional' ? 5 : 0)),
    content_quality_score: Math.min(90, 75 + (wordCount > 100 ? 15 : 0)),
    engagement_score: Math.min(85, 70 + (params.urgency_level === 'high' ? 10 : 0) + (params.include_cta ? 5 : 0))
  };
}

async function generateRecommendations(_content: string, params: ContentCreateParams): Promise<{
  variations?: string[];
  optimization_tips?: string[];
  a_b_test_suggestions?: string[];
}> {
  const recommendations: {
    variations?: string[];
    optimization_tips?: string[];
    a_b_test_suggestions?: string[];
  } = {};
  
  if (params.content_type === 'email') {
    recommendations.variations = [
      'Версия с более ярким заголовком',
      'Версия с дополнительными преимуществами',
      'Версия с социальными доказательствами'
    ];
    
    recommendations.optimization_tips = [
      'Добавьте персонализацию в тему письма',
      'Используйте эмодзи для повышения открываемости',
      'Сократите длину превью текста'
    ];
    
    recommendations.a_b_test_suggestions = [
      'Тестируйте разные CTA кнопки',
      'Сравните короткую и длинную версии',
      'Тестируйте время отправки'
    ];
  }
  
  return recommendations;
}

function calculateReadTime(content: string): string {
  const wordCount = content.split(' ').length;
  const readingTime = Math.ceil(wordCount / 200); // 200 words per minute
  return `${readingTime} мин`;
}

function extractKeywords(content: string): string[] {
  const text = content.toLowerCase();
  const keywords: string[] = [];
  
  // Travel-related keywords
  if (text.includes('франция') || text.includes('париж')) keywords.push('путешествия');
  if (text.includes('осень') || text.includes('осенью')) keywords.push('сезон');
  if (text.includes('скидка') || text.includes('акция')) keywords.push('предложения');
  if (text.includes('билет') || text.includes('бронирование')) keywords.push('бронирование');
  
  return keywords.length > 0 ? keywords : ['контент', 'email', 'маркетинг'];
}

function extractPersonalizationTokens(content: string): string[] {
  const tokens: string[] = [];
  
  if (content.includes('{{')) {
    // Extract placeholder tokens
    const matches = content.match(/{{([^}]+)}}/g);
    if (matches) {
      tokens.push(...matches.map(m => m.replace(/[{}]/g, '')));
    }
  }
  
  // Add common personalization tokens
  if (content.includes('Дорогие') || content.includes('Dear')) {
    tokens.push('имя_пользователя');
  }
  
  return tokens;
}