/**
 * Design Specialist Tools - Modular Architecture
 * Exports all design specialist tools and utilities
 */

// Design Specialist does not generate asset manifest or technical specification
// These are generated by Content Specialist and loaded by Design Specialist

// Export all tools
export { loadDesignContext } from './design-context';
export { processContentAssets } from './asset-processor';
export { generateTemplateDesign } from './ai-template-designer';
export { generateMjmlTemplate } from './mjml-generator';
export { readTechnicalSpecification, documentDesignDecisions } from './design-documentation';
export { generatePreviewFiles } from './preview-generator';
export { analyzePerformance } from './performance-analyzer';
export { generateComprehensiveDesignPackage } from './design-package-generator';
export { createDesignHandoff } from './design-handoff';
export { enhanceEmailDesign } from './html-validator';
export { validateAndCorrectHtml } from './ai-html-validator';

// Asset Manifest and Technical Specification are generated by Content Specialist
// Design Specialist only reads them, not generates them

// Export types and utilities
export * from './types';
export * from './design-helpers';

// Import all tools for registry
import { loadDesignContext } from './design-context';
import { processContentAssets } from './asset-processor';
import { generateTemplateDesign } from './ai-template-designer';
import { generateMjmlTemplate } from './mjml-generator';
import { readTechnicalSpecification, documentDesignDecisions } from './design-documentation';
import { generatePreviewFiles } from './preview-generator';
import { analyzePerformance } from './performance-analyzer';
import { generateComprehensiveDesignPackage } from './design-package-generator';
import { createDesignHandoff } from './design-handoff';
import { enhanceEmailDesign } from './html-validator';
import { validateAndCorrectHtml } from './ai-html-validator';
import { finalizeDesignAndTransferToQuality } from '../../core/specialist-finalization-tools';
// Import transfer function
import { transferToQualitySpecialist } from '../../core/transfer-tools';

/**
 * All Design Specialist tools in recommended workflow order
 * CORRECTED: Asset Manifest and Technical Specification are generated by Content Specialist
 */
export const designSpecialistTools = [
  loadDesignContext,             // Step 0: Load context from handoff files
  readTechnicalSpecification,    // Step 1: Read tech specs (generated by Content Specialist)
  processContentAssets,          // Step 2: Process content assets (reads from manifest generated by Content Specialist)
  generateTemplateDesign,        // Step 3: AI template design
  generateMjmlTemplate,          // Step 4: MJML generation
  documentDesignDecisions,       // Step 5: Document decisions
  generatePreviewFiles,          // Step 6: Generate previews
  validateAndCorrectHtml,        // Step 7: HTML validation and correction
  analyzePerformance,            // Step 8: Performance analysis
  generateComprehensiveDesignPackage, // Step 9: Comprehensive package
  createDesignHandoff,           // Step 10: Create handoff for QA
  finalizeDesignAndTransferToQuality, // Step 11: CRITICAL - Finalize context
  transferToQualitySpecialist    // Step 12: CRITICAL - Transfer to Quality Specialist
];

/**
 * Design Specialist workflow order reference
 * CORRECTED: Asset Manifest and Technical Specification are generated by Content Specialist
 */
export const designWorkflowSteps = [
  'loadDesignContext',           // Step 0: Load context from handoff files
  'readTechnicalSpecification',  // Step 1: Read tech specs (generated by Content Specialist)
  'processContentAssets',        // Step 2: Process content assets (reads from manifest generated by Content Specialist)
  'generateTemplateDesign',      // Step 3: AI template design
  'generateMjmlTemplate',        // Step 4: MJML generation
  'documentDesignDecisions',     // Step 5: Document decisions
  'generatePreviewFiles',        // Step 6: Generate previews
  'validateAndCorrectHtml',      // Step 7: HTML validation and correction
  'analyzePerformance',          // Step 8: Performance analysis
  'generateComprehensiveDesignPackage', // Step 9: Comprehensive package
  'createDesignHandoff',         // Step 10: Create handoff for QA
  'finalizeDesignAndTransferToQuality' // Step 11: CRITICAL - Transfer to Quality Specialist
];

/**
 * Tool registry mapping for easy access
 * CORRECTED: Asset Manifest and Technical Specification are generated by Content Specialist
 */
export const designToolRegistry = {
  loadDesignContext,
  readTechnicalSpecification,
  processContentAssets,
  generateTemplateDesign,
  generateMjmlTemplate,
  documentDesignDecisions,
  generatePreviewFiles,
  validateAndCorrectHtml,
  analyzePerformance,
  generateComprehensiveDesignPackage,
  createDesignHandoff,
  finalizeDesignAndTransferToQuality
}; 