/**
 * Design Specialist Tools - Modular Architecture
 * Exports all design specialist tools and utilities
 */

// Design Specialist does not generate asset manifest or technical specification
// These are generated by Content Specialist and loaded by Design Specialist

// Export all tools - V3 ONLY (legacy tools removed)
export { loadDesignContext } from './design-context';
export { processContentAssets } from './asset-processor';
export { readTechnicalSpecification, documentDesignDecisions } from './design-documentation';
export { generatePreviewFiles } from './preview-generator';
export { analyzePerformance } from './performance-analyzer';
export { generateComprehensiveDesignPackage } from './design-package-generator';
export { createDesignHandoff } from './design-handoff';
export { validateAndCorrectHtml } from './ai-html-validator'; // Uses integrated OpenAI API call, not separate Agent

// Asset Manifest and Technical Specification are generated by Content Specialist
// Design Specialist only reads them, not generates them

// Export types and utilities
export * from './types';
export * from './design-helpers';

// Import all tools for registry - V3 ONLY (legacy tools removed)
import { loadDesignContext } from './design-context';
import { processContentAssets } from './asset-processor';
import { readTechnicalSpecification, documentDesignDecisions } from './design-documentation';
import { generatePreviewFiles } from './preview-generator';
import { analyzePerformance } from './performance-analyzer';
import { generateComprehensiveDesignPackage } from './design-package-generator';
import { createDesignHandoff } from './design-handoff';
import { validateAndCorrectHtml } from './ai-html-validator'; // Uses integrated OpenAI API call, not separate Agent
import { finalizeDesignAndTransferToQuality } from '../../core/specialist-finalization-tools';
// Import ENHANCED V3 tools with AI agents
import { analyzeContentForDesign } from './content-intelligence-analyzer';
import { generateTemplateDesign as generateAdaptiveDesign } from './ai-template-designer';
import { generateMjmlTemplate as generateEnhancedMjmlTemplate } from './mjml-generator';

/**
 * All Design Specialist tools in recommended workflow order - V3 ONLY VERSION
 * Legacy tools removed, only V3 enhanced tools for intelligent content analysis and adaptive design
 */
export const designSpecialistTools = [
  loadDesignContext,             // Step 0: Load context from handoff files
  analyzeContentForDesign,       // Step 1: V3 - Intelligent content analysis
  readTechnicalSpecification,    // Step 2: Read tech specs (generated by Content Specialist)
  processContentAssets,          // Step 3: Process content assets (reads from manifest generated by Content Specialist)
  generateAdaptiveDesign,        // Step 4: V3 - AI-powered template design (uses templateDesignAgent)
  generateEnhancedMjmlTemplate,  // Step 5: V3 - AI-powered MJML generation (uses mjmlGenerationAgent)
  documentDesignDecisions,       // Step 6: Document decisions
  generatePreviewFiles,          // Step 7: Generate previews
  validateAndCorrectHtml,        // Step 8: HTML validation and correction
  analyzePerformance,            // Step 9: Performance analysis
  generateComprehensiveDesignPackage, // Step 10: Comprehensive package
  createDesignHandoff,           // Step 11: Create handoff for QA
  finalizeDesignAndTransferToQuality // Step 12: CRITICAL - Finalize design context
];

/**
 * Design Specialist V3 workflow order reference - V3 ONLY VERSION
 * Legacy tools removed, only V3 enhanced tools for intelligent content analysis and adaptive design
 */
export const designWorkflowSteps = [
  'loadDesignContext',           // Step 0: Load context from handoff files
  'analyzeContentForDesign',     // Step 1: V3 - Intelligent content analysis
  'readTechnicalSpecification',  // Step 2: Read tech specs (generated by Content Specialist)
  'processContentAssets',        // Step 3: Process content assets (reads from manifest generated by Content Specialist)
  'generateAdaptiveDesign',      // Step 4: V3 - AI-powered template design (uses templateDesignAgent)
  'generateEnhancedMjmlTemplate', // Step 5: V3 - AI-powered MJML generation (uses mjmlGenerationAgent)
  'documentDesignDecisions',     // Step 6: Document decisions
  'generatePreviewFiles',        // Step 7: Generate previews
  'validateAndCorrectHtml',      // Step 8: HTML validation and correction
  'analyzePerformance',          // Step 9: Performance analysis
  'generateComprehensiveDesignPackage', // Step 10: Comprehensive package
  'createDesignHandoff',         // Step 11: Create handoff for QA
  'finalizeDesignAndTransferToQuality'  // Step 12: CRITICAL - Finalize design context
];

/**
 * Tool registry mapping for easy access - V3 ONLY VERSION
 * Legacy tools removed, Asset Manifest and Technical Specification are generated by Content Specialist
 */
export const designToolRegistry = {
  loadDesignContext,
  analyzeContentForDesign,
  generateAdaptiveDesign,
  readTechnicalSpecification,
  processContentAssets,
  generateEnhancedMjmlTemplate,
  documentDesignDecisions,
  generatePreviewFiles,
  validateAndCorrectHtml,
  analyzePerformance,
  generateComprehensiveDesignPackage,
  createDesignHandoff,
  createHandoffFile: createDesignHandoff, // Alias for backward compatibility
  finalizeDesignAndTransferToQuality
}; 